### ISSUE TITLE
Fix bug from `transformer.ipynb` in `/experiments` 

### ISSUE THREAD

**Issue by A-baoYang** [LongmaoTeamTf/deep_recommenders#12]
Hi, thank you so much for open sourcing your project, it helps me a lot!!
Here I just have one simple bug to report:

---

Source: 3rd code cell from notebook

- Original:
```
outputs = Transformer(
    vocab_size, 
    model_dim, 
    n_heads=2, 
    encoder_stack=2,
    decoder_stack=2, 
    feed_forward_size=50
)([encoder_inputs, decoder_inputs])
```

After ran the notebook and traced your code (`deep_recommenders/keras/models/nlp/Transformer.py`), 
the input of Transformer class object needs 2 parameters (encoder_inputs, decoder_inputs), it should not be a list.

- Revised:
```
outputs = Transformer(
    vocab_size, 
    model_dim, 
    n_heads=2, 
    encoder_stack=2,
    decoder_stack=2, 
    feed_forward_size=50
)(encoder_inputs, decoder_inputs)
```

**Comment by SharpCX** [comment]
We have fix the issues, thx.
